### ISSUE TITLE
How is this used with table rows?

### ISSUE THREAD

**Issue by tschundeee** [bevacqua/dragula#112]
dragula({ containers: [document.getElementById("productsTable")], delay: 200 });

allows me to drag the whole table? I want to sort tr elements

**Comment by tschundeee** [comment]
Okay I saw that using the <tbody> element is the key.

**Comment by bevacqua** [comment]
For future reference, your container needs to be the immediate parent of the elements you want to be draggable. In this case, that'd be the `tbody`.

**Comment by spapaseit** [comment]
Hi, 
I want to allow the user to reorder `tr` in a `table` by means f drag and drop.

I have marked the `tbody` of a table with the classes `drag-source drop-target` , and I initialize dragula as follows:

```
constructor() {
    let dragApi = dragula({
            isContainer: el => {
                if (!el) {
                    return false;
                }
                if (dragApi.dragging) {
                    return el.classList.contains("drop-target");
                }
                return el.classList.contains("drag-source");
            },
            revertOnSpill: true,
            delay: 200
        });

        this.trackDrop(dragApi);
    }

    trackDrop(dragApi) {
        dragApi.on("drop", (el, container, source) => {
            dragApi.cancel();
        });
    }
```

This is part of an [Aurelia](http://aurelia.io) application, and at the time of the dragula initialization the DOM is not yet available; that's why I don't pass the `containers` option directly into dragula.

### The problem
I cannot drop the `tr` back into the table on a new position. The drag _is always reverted_. If I turn `revertOnSpill` off, the drag never ends, and the call to `dragApi.cancel()` ends up with a `Maximum call stack exceeded`

How can I achieve reordering of the table `tr`?
