### ISSUE TITLE
Dragging <a> and <img> behaves poorly on Firefox

### ISSUE THREAD

**Issue by lkrids** [bevacqua/dragula#155]
It seems like the merge from no-delay-clicks to master didn't work.  On master in Firefox I'm not able to drag ```<a>``` or ```<img>``` tags.

master (doesn't work): http://jsbin.com/pejixahala/edit?html,output
no-delay-clicks (works): http://jsbin.com/rojuwakega/edit?html,output

**Comment by bevacqua** [comment]
I can confirm that dragging `<a>` elements from the [demo page][1] behaves awkwardly on Firefox.

[1]: http://bevacqua.github.io/dragula/

**Comment by lkrids** [comment]
it's missing the e.preventDefault() on grab.

https://github.com/bevacqua/dragula/blob/no-delay-clicks/dragula.js#L83

I'm not sure how you are minifying the files otherwise I would have sent a pr.

**Comment by bevacqua** [comment]
Even with a `preventDefault` on grab, this still happens sometimes.

**Comment by lkrids** [comment]
It seems to fix it for me.  Are you only looking in Firefox desktop?

**Comment by bevacqua** [comment]
Nevermind. That was a mistake. I wrote a faulty check. This fixes it! Woo

**Comment by bevacqua** [comment]
I had:

```js
if (e.type === 'mousemove') {
  e.preventDefault();
}
```

But I needed to check for `mousedown` instead of `mousemove`. Reason for conditional is that `preventDefault` on `touchmove` _(and presumably `MSPointerMove`)_ makes it impossible to follow links, because there is no `click` event being raised afterwards like in desktop.

**Comment by lkrids** [comment]
Awesome!  That makes sense, didn't think about the touch events.

**Comment by bevacqua** [comment]
Thanks for all the work. This is an important fix! I've compiled a few details on [how you can contribute][1].

Basically the `dist` files are created by using the `browserify` tool via `npm run build` (or `npm start`, which sets up a _watch_ that rebuilds the `dist` files whenever the source code changes). So to contribute you edit source files directly and run npm run build to test your changes (but you don't commit changes to `dist`, because that's autogenerated).

Hope that makes sense. If it doesn't, one option could be that you [edit the `contributing.markdown`][1] file adding any details that you feel are missing. That'd help a lot moving forward!

[1]: https://github.com/bevacqua/dragula/blob/master/contributing.markdown

**Comment by bevacqua** [comment]
Deployed as `3.0.3`! Thanks again.
