### ISSUE TITLE
Can't load dragula in <head>

### ISSUE THREAD

**Issue by rfunduk** [bevacqua/dragula#16]
It seems when loading dragula in `<head>`, the local `body` variable is `null`, which causes all kinds of problems. It seems this is due to `document.body` being `null` at the time `body` is defined: https://github.com/bevacqua/dragula/blob/master/dragula.js#L5

To state the obvious -- I know the ideal solution here is "don't put your scripts in `<head>`", but unfortunately I have a very large codebase that does exactly the opposite :expressionless:... Maybe dragula could support this? I'd be happy to attempt a PR if you're amenable to it.

Here's a demo showing the problem: http://ryanfunduk.com/dragula-test.html
Same page but loading at EOB: http://ryanfunduk.com/dragula-works.html

Thanks for dragula, btw! It's looking like the drag&drop lib of my dreams :)

**Comment by ferdinandsalis** [comment]
I am experiencing the same problem. btw, @bevacqua thanks you for dragula. You have perfect timing :)

**Comment by DaleGardner** [comment]
Placing scripts in the head is fine, that's where they belong.

You just have to add the "defer" attribute to the script tag, and it will load the same as if it were placed before the closing body tag. It is supported on all browsers: http://caniuse.com/#feat=script-defer

Even if Dragula could be updated to work otherwise, I would still recommend against loading it in the head without defer. It will reduce your page load performance if you don't defer it.

I modified your dragula-test.html by adding the defer attribute and it works fine.
```<script src="https://rawgit.com/bevacqua/dragula/master/dist/dragula.js" defer></script>```

**Comment by rfunduk** [comment]
The problem is I can't do that either, it breaks various things in the existing codebase that I'd... rather not yakshave right now :)
