### ISSUE TITLE
Only allow one element to drop

### ISSUE THREAD

**Issue by davidbarker1** [bevacqua/dragula#230]
Hi,

I'm trying to set up a droppable container which only allows one element to be dropped.  After the container has an element dropped, any subsequent drop would cause the current dropped item to be programmatically dragged and dropped back to the originating container.

I can obviously manipulate the DOM but I would prefer a more intuitive experience to indicate the dropped area only allows one item.

This obviously isn't a feature of dragula but is it possible using the drop event?

Cheers

**Comment by Myrdivar** [comment]
Hi,

I'm interested in this topic too. Any info on how to achieve that?

**Comment by ben-pr-p** [comment]
Try removing the container from drake.containers after it has something dropped on it

**Comment by Myrdivar** [comment]
Thanks for the reply ben. The first solution could work but in my case I need to leave the destination container in order to drag and drop away the only one element that should be present.

The second one is the solution I already adopted but sometimes it acts strangely. I haven't figured it out yet but once in a while when I drop an element the drop event fires, the attribute is set but the element dropped doesn't end up in the container (and in the dom).

**Comment by ben-pr-p** [comment]
Ok you could change the class of the container, so that initially it has an `accepting` class, but after one element is dropped it changes to `leaving`. Then you change it back and forth

**Comment by bevacqua** [comment]
Use Slack for support requests. See #248.
