### ISSUE TITLE
Licensing: Switch to GPLv3?

### ISSUE THREAD

**Issue by bevacqua** [bevacqua/dragula#322]
I've been approached by the folks at UpLabs to consider changing the licensing scheme in `dragula` from `MIT` to `GPLv3` -- essentially making `dragula` an open-source solution that can be used commercially by purchasing a commercial license.

Dragula would still be open-source and free to use in open-source projects. I can't think of a lot of drawbacks here to be honest. Companies that rely on `dragula` can probably afford purchashing a one-time license. I could definitely use the help (money), and it would certainly motivate me to grow the open-source project so I think everybody would win.

That being said I have my fair share of doubt in the matter, so I chose to post an issue here first and see what others think about this.

**Comment by mxstbr** [comment]
I've been thinking about doing something similar for a project of mine, and thought about using a [CC-BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/) license. Why would you use GPLv3 - what are the benefits and the drawbacks?

**Comment by richardprice** [comment]
I use Dragula in a few projects - Id be willing to buy a commercial license where the project is commercial in nature, but for all the rest I would simply dump a GPLv3 licensed Dragula. Which would bring me to the interesting situation of investigating other options and potentially not sending money your way for the commercial license at all.

**Comment by davidyezsetz** [comment]
I can't see a drawback and you certainly deserve the help (money) for what you've created

**Comment by ate** [comment]
We are currently using Dragula in a prototype for a next release of our [product](http://www.onehippo.org). And we are very happy with it!

However, as our product itself is open-source under the Apache License (ASL2.0), if the license for Dragula is changed to GPLv3 we no longer will be able to use it, as GPLv3 is not compatible with ASL2.0.
As a product vendor we make our money through support subscriptions only (which also gives access to additional Enterprise features of our product), it would not be a problem to pay _ourselves_ some usage (licensing) fee. But we cannot, and don't want to either, enforce this on our open-source community.
For our product users using and embedding GPLv3 licensed software has viral consequences, forcing our own product as well as any downstream usages to become GPLv3 automatically too.
This would be a hard blocker for us and require us to find an alternative solution.
That really would be a pitty though as we really do like Dragula a lot.

Of course changing the license is your own choice to make, and I definitely understand the wish or need to somehow make money out of it, just as we as a company are doing.
There might be alternative ways though, and I'd be happy to discuss that further if you would be interested.

For now I just wanted to voice our concern and make clear that changing to GPLv3 does have drawbacks for some type of usages.

**Comment by mxstbr** [comment]
@ate that's very interesting, I thought the reason for using GPLv3 was that it allows commercial and non-commercial open source usage for free (as in beer), but not closed source.

Apparently that's not correct - what license would you recommend for that use case?

**Comment by richardprice** [comment]
@mxstbr there is nothing in the GPLv3 that prevents you using something commercially, so long as anything distributed along with the GPLv3 licensed code also falls under the GPLv3.

If I'm using Dragula alongside another library which is under a different license, then we are into a grey area when it comes to a web page - in some ways it could be classed as a collection, and therefore the GPLv3 doesn't apply to other libraries (in the same way that a Linux distribution can contain apps using different licenses), but we do have the added issue that there is no clear separation of code in JS, so the code inclusion issue which triggers the GPL elsewhere may also come into play here merely by using a GPL library in your page.

There are also the "political" considerations of using the GPLv3 specifically - a lot of devs will avoid GPLv3 stuff purely because of the politics.

If you are looking for a license which allows you to be much more specific in who gets to do what, then you should be looking at the Creative Commons collection of licenses, which basically cover all bases.

**Comment by mxstbr** [comment]
@richardprice I've looked at [CC-BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/), but CC specifically says one shouldn't use their licences for source code...

**Comment by TehShrike** [comment]
It is possible to sell a commercial license without defaulting to a restrictive license.  This is something I've seen Patrick McKenzie advocate for:

https://twitter.com/patio11/status/428636702530633728
https://twitter.com/patio11/status/685407912559128577

As a business I'm willing to pay for a commercial license, but I would never even get to the "download it and see how it works in our app by implementing it on one screen" step if the license was GPL.

Speaking for myself as an open source developer, I try to avoid pulling in GPL code into even my open source projects.  It's a potential headache I don't want to have to think about or inflict upon the people using my code.

**Comment by richardprice** [comment]
@mxstbr you could always make your own license by stating what license terms apply under what circumstances, for example:

When used in a non-commercial manner (as defined below), this source code is available for use and distribution under terms identical to the MIT license.

When used in a commercial manner (as defined below), this source code is available for use and distribution under the GPLv3 license or other commercial license terms available on request from the original author.

These clauses apply at all times and to all recipients of the code.

Non-commercial use is defined as...

Commercial use is defined as...

**Comment by PhiLhoSoft** [comment]
I agree with the above remarks. GPL is a viral license, so GPL licensed libraries are often avoided by open source projects, although I am not sure how it works for scripting languages (it is a bit clearer with binary programs).
Yes, you can earn some money with this scheme, which is a good thing. But you will loose users, existing or potential; lot of them will look at other similar libraries; your must be above the lot to get a chance to succeed...
Will the license be applied starting at a given version, or will it be applied retroactively? In other words, do existing projects using Dragula will be forced to change their license (or to use another library), even if they use an older version?

At work, we use a commercial library, Highcharts, because we think it is really better than the alternatives. They use a CC license for open source projects, but @mxstbr says that's wrong... :smile: 
http://shop.highsoft.com/highcharts

Another JS library went the commercial route: they still release the legacy version (still updated, at least for bug fixes) as "Community edition", and they sell a "Toolkit edition" with more features:
https://jsplumbtoolkit.com/purchase
As we don't use the advanced features, we remain at the community edition.

There are a number of possible schemes. Outside of GPL... :wink:

**Comment by bevacqua** [comment]
Licensing is not changing.

**Comment by mxstbr** [comment]
@bevacqua what made you change your mind?

**Comment by bevacqua** [comment]
I don't want to hurt the community for the sake of making a few bucks -- I thought this would've been less pervasive

**Comment by ate** [comment]
That is good news and thank you @bevacqua for your consideration.
We'll continue to be a happy user and supporter of Dragula!

**Comment by bigteejay** [comment]
Any thoughts as to a donation mechanism on the main page here?

**Comment by bevacqua** [comment]
See https://patreon.com/bevacqua and [this paypal donation link](https://www.paypal.com/uk/cgi-bin/webscr?cmd=_flow&SESSION=bvjUHABUVZOqTww2Xc1p-WtUV6ee8nvNIV4qukmcci46sSUrO3tFZV_Bps0&dispatch=5885d80a13c0db1f8e263663d3faee8d6625bf1e8bd269586d425cc639e26c6a)

**Comment by bigteejay** [comment]
I get an error when I click on the paypal donation link provided (see attached)...
              

Date: Tue, 29 Mar 2016 19:56:07 -0700

**Comment by bevacqua** [comment]
Fixed.
