### ISSUE TITLE
How should I save the new order?

### ISSUE THREAD

**Issue by luctus** [bevacqua/dragula#36]
I just can't figure it out what is the best way to call an ajax api to save the new order... any hint?

**Comment by bevacqua** [comment]
What I do is have an `order` or `position` or whatever field. It's `null` by default. Whenever something is ordered, I call an API and tell it what actual position I want the item to be placed at, e.g: `parent.children.indexOf(el)`.

The backend API does the following

- Assign a starting weight to every `null` element, step `10000`
- If the requested element position is `0`, then it's weight is the weight of the least "heavy" item, minus `10000`
- If the requested position is the last one, then the weight is the last weight plus `10000`
- If it's somewhere in between, then it's the sum of the previous and the next elements, divided by two. E.g an item that goes in position 1 between weights `10000` and `20000` gets `15000`
- After all of the above, check if the item is actually in the requested index. If not, the weights are no longer "stable", and you'll need to go through the list, assigning a weight of `10000 * i` to each item, and saving each one of them

This is my recommended approach because you'll generally just update a single element in the db, which allows for concurrent users modifying the list at the same time. Sending the whole order is just asking for trouble

**Comment by elgubenis** [comment]
which ```children``` are you referring to? i tried ```$(sibling).parent()[0].children.indexOf(sibling)``` and ```-1``` but it says indexOf is not a function, even though if i console log the children i get all the children.

**Comment by timwis** [comment]
For anyone who comes here from searching, here's the function I use:

```javascript
function getIndexInParent (el) {
  return Array.from(el.parentNode.children).indexOf(el)
}
```

For those of you using immutable global state (redux/choo/etc), here's a helper function for reordering an item in an array immutably:

```javascript
// Move item in an array immutably
function moveItem (array, fromIndex, toIndex) {
  const arrayCopy = array.slice()
  const item = arrayCopy[fromIndex]
  arrayCopy.splice(fromIndex, 1) // remove field that's moving
  arrayCopy.splice(toIndex, 0, item) // add it back
  return arrayCopy
}
```

**Comment by DimitriMikadze** [comment]
Hey, thanks for writing your solution. 

how to get fromIndex and toIndex while drop, in vanilla js or in react ?

**Comment by paddotk** [comment]
@timwis Where does the `fromIndex` come from?

**Comment by paddotk** [comment]
I figured I needed the original index of the dragged item, as the 'drop' event handler returns the el at the new position in its container. It seems that (at least in my scenario) it can be done as such:

```
const dragHandler = dragula([container])
dragHandler.on('drop', this.onListItemDrop);

// If the draggable items are e.g. <spans>with plain text in them
const onListItemDrop = (el, target, source, sibling) => {
	const updatedContainer = [].slice.call(target.childNodes).map((span) => li.innerHTML);
}
```
This simply looks at the contents of the updated container, and makes an array out of its items.
