### ISSUE TITLE
Issue when calling cancel in drop callback

### ISSUE THREAD

**Issue by gsouf** [bevacqua/dragula#419]
I'm using version 3.7.1 and i'm getting the following issue:

```js
drake.on('drop', function(){
    drake.cancel();
});
```
```
Uncaught RangeError: Maximum call stack size exceeded
@ atoa.js:1(anonymous function) 
@ emitter.js:43thing.emit 
@ emitter.js:38cancel 
@ dragula.js:297(anonymous function) 
@ application.vue:27emitter
@ emitter.js:47forEach @ (program):959(anonymous function) 
@ emitter.js:46thing.emit 
@ emitter.js:38cancel 
@ dragula.js:297
```

Please note that the following works perfectly:

```js
drake.on('drop', function(){
    drake.cancel(true);
});
```

**Comment by bevacqua** [comment]
What are you hoping to accomplish by canceling on drop?

**Comment by gsouf** [comment]
I dont want the dom to be updated, instead I want to know what element was droped and in what container it was droped and I can get information to update my data that will also update the dom

**Comment by bevacqua** [comment]
We need a better solution for that, but this is not it.

**Comment by gsouf** [comment]
@bevacqua Why are you closing the issue if you need a better solution?

**Comment by bevacqua** [comment]
calling `cancel` on drop is not supported, please open a new issue asking about what you're attempting to accomplish by doing so.

**Comment by gsouf** [comment]
In #101 you asked me to fill an issue, that's what I did and you close it

**Comment by nerdymax** [comment]
this issue definitely needs to be solved. we want to update the state and UI accordingly, not with Dragula, in some cases.

**Comment by epos** [comment]
Agreed, in MVVM frameworks this is definitely something we want.

**Comment by vitobotta** [comment]
I have this problem using Dragula with Vue.js. Basically I have to cancel the drop within the drop even so I can gather the info about the drag & drop and update the underlying data in Vue.js. Otherwise the Vue.js data and the DOM will go out of sync. I am pretty sure this happens with other libraries/frameworks as well, as @epos mentioned. If I do cancel(true) it doesn't work properly because once I update the Vue.js data Dragula gets "confused" as to which item I am dragging and it seems I am dragging the wrong item. LOL I don't know how to explain this... does it make any sense? :D If I do cancel(false) to prevent Dragula from reverting it gets in a sort of endless loop.

**Comment by leif81** [comment]
Someone else asked how to do this here http://stackoverflow.com/questions/35528488/angular-dragula-confirm-on-drop-event/

This seems like a valid issue to me.

**Comment by leif81** [comment]
Actually this sounds like a dupe of #188.
