### ISSUE TITLE
How I can drag element from div in main document to another div inside iframe ??

### ISSUE THREAD

**Issue by abdulkareemmnv** [bevacqua/dragula#476]
> Please only use GitHub issues for bug reports and feature requests.
>
> - [ ] Read the [contributing guidelines][contrib]
> - [ ] Bug reports containing repro steps are likely to be fixed faster
> - [ ] Feature requests should be multi-purpose, describe use cases
> - [ ] For support requests or questions, please refer to [our Slack channel][slack]

[contrib]: https://github.com/bevacqua/dragula/blob/master/.github/contributing.markdown
[slack]: https://dragula-slackin.herokuapp.com/

**Comment by paddotk** [comment]
While I'm not a 100% sure this could work for same-origin iframes (although why would you do that), iframes with an external source (another web site/server address) are protected against modifying its contents.

Because of security restrictions on iframes in general, I would think this isn't possible for same-origin iframes either.
