### ISSUE TITLE
Click handler in demo doesn't fire on FireFox 38.0.5

### ISSUE THREAD

**Issue by dougludlow** [bevacqua/dragula#96]
![firefox-click-bug](https://cloud.githubusercontent.com/assets/733821/8482856/90561cce-20a9-11e5-9d54-a699053372e1.gif)

**Comment by bevacqua** [comment]
Could you try to figure out a fix?

**Comment by dougludlow** [comment]
Sure, no problem. Might be a little bit, I'm busy on another project.

**Comment by qq286735628** [comment]
try make `options.delay` bigger, like 500 or 800

early, it can not fire `click` because event 'mouseup' fire at **_mirror**, not **_item**.
**_item** fire `click` need fire `mousedown` and `mouseup`.

so i delay **_mirror** create, let **_item** have enough time to fire `mouseup` to fire `click`.

the better solution is create **_mirror** when `mousemove` replace delay

**Comment by bevacqua** [comment]
@qq286735628 PR? :)

**Comment by qq286735628** [comment]
i try but fail.

it will change `start()` and `end()` logic.
I'm not understand why `start()` and `end()` will exec in `grab`, expecially `end()` will exec in `start()`
